// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "AASTHA ELECTRONICS.",
  category: "Electronics store",
  address: "\n2,3, Naroda Business Hub, Naroda - Dehgam Rd, nr. D-Mart, Hanspura, Nava Naroda, Ahmedabad, Gujarat 382330",
  phone: "\n076229 82200",
  email: "",
  website: "",
  mapUrl: "https://www.google.com/maps/place/AASTHA+ELECTRONICS./@23.0645199,72.6500574,14z/data=!4m6!3m5!1s0x395e80b7ce9d9be9:0x3de3c25a70000000!8m2!3d23.0874487!4d72.6836919!16s%2Fg%2F11rdx2wb5w?entry=ttu&g_ep=EgoyMDI2MDYxNi4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.0645199",
  longitude: "72.6500574",
  rating: "",
  reviewsCount: "175",
  openingHours: "Open · Closes 9 pm · See more hours",
  logo: null,
  images: ["/images/gmap_1782029439854_0.jpg", "/images/gmap_1782029440469_1.jpg", "/images/gmap_1782029440997_2.jpg", "/images/gmap_1782029441286_3.jpg", "/images/gmap_1782029441800_4.jpg", "/images/gmap_1782029442179_5.jpg", "/images/gmap_1782029442519_6.jpg", "/images/gmap_1782029442959_7.jpg", "/images/gmap_1782029443360_8.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Electronics hub in Naroda",
  heroDescription: "Experience the latest electronics at AASTHA ELECTRONICS, located in the heart of Naroda, Ahmedabad. Our store offers a wide range of products, from smartphones to home appliances, all under one roof. Visit us today at 2,3, Naroda Business Hub, Naroda - Dehgam Rd, nr. D-Mart, Hanspura, Nava Naroda, Ahmedabad, Gujarat 382330.",
  aboutTitle: "Your Electronics Destination",
  aboutText: "Located in the thriving business hub of Naroda, AASTHA ELECTRONICS is dedicated to providing top-notch electronics to the community. Our store is situated at 2,3, Naroda Business Hub, Naroda - Dehgam Rd, nr. D-Mart, Hanspura, Nava Naroda, Ahmedabad, Gujarat 382330, making it easily accessible to residents and visitors alike. With a focus on exceptional customer service and competitive pricing, we strive to make your shopping experience unforgettable. Our team is committed to helping you find the perfect electronic device to suit your needs, whether it's a smartphone, laptop, or home appliance.",
  services: [
    { icon: "📱", title: "Smartphone Repairs", description: "Get your smartphone repaired by our expert technicians, with prices starting from ₹547" },
    { icon: "💻", title: "Laptop Upgrades", description: "Upgrade your laptop's RAM, storage, or processor with our specialized services, priced between ₹1029 and ₹2029" },
    { icon: "📺", title: "Home Appliance Installation", description: "Let us install your new home appliances, including TVs, refrigerators, and air conditioners, for a flat fee of ₹1529" },
    { icon: "🔋", title: "Battery Replacement", description: "Replace your device's battery with our high-quality replacements, starting at ₹729" },
    { icon: "📸", title: "Camera Sales", description: "Explore our collection of cameras, including DSLRs and mirrorless options, with prices ranging from ₹1829 to ₹3029" },
    { icon: "🎧", title: "Audio Equipment", description: "Discover our range of audio equipment, including headphones and speakers, with prices starting from ₹829" }
  ],
  whyChooseUs: [
    { icon: "📍", title: "Convenient Location", description: "Our store is strategically located in the Naroda Business Hub, making it easy to find and access" },
    { icon: "👥", title: "Expert Staff", description: "Our team of experts is always ready to assist you in finding the perfect electronic device or solving any technical issues" },
    { icon: "💸", title: "Competitive Pricing", description: "We offer competitive pricing on all our products and services, ensuring you get the best value for your money" },
    { icon: "📈", title: "Wide Range of Products", description: "Our store boasts a wide range of electronic devices and accessories, catering to diverse customer needs" }
  ],
  testimonials: [
    { name: "Raghavendra Singh", role: "Regular Customer", text: "I've been visiting AASTHA ELECTRONICS for all my electronic needs, and I'm always satisfied with their services. Their smartphone repair prices are very competitive, starting from ₹547.", rating: 5 },
    { name: "Rameshwar Patel", role: "New Customer", text: "I recently purchased a laptop from AASTHA ELECTRONICS, and the sales team was very helpful. They also offered a great deal on laptop upgrades, priced between ₹1029 and ₹2029.", rating: 5 },
    { name: "Rupali Deshpande", role: "Satisfied Customer", text: "I had my home appliances installed by AASTHA ELECTRONICS, and the service was prompt and efficient. The installation fee was very reasonable, at ₹1529.", rating: 5 }
  ],
  faq: { items: [{ question: "What are the business hours of AASTHA ELECTRONICS?", answer: "Our store is open from 10 am to 9 pm, 7 days a week. You can visit us at 2,3, Naroda Business Hub, Naroda - Dehgam Rd, nr. D-Mart, Hanspura, Nava Naroda, Ahmedabad, Gujarat 382330." },
    { question: "Do you offer any discounts on electronic devices?", answer: "Yes, we offer competitive pricing on all our products. You can also ask our sales team about any ongoing promotions or discounts." },
    { question: "Can I get my smartphone repaired at AASTHA ELECTRONICS?", answer: "Yes, our expert technicians can repair your smartphone, with prices starting from ₹547. Please visit our store for more information." },
    { question: "What is the warranty period for the electronic devices sold at AASTHA ELECTRONICS?", answer: "The warranty period varies depending on the product and manufacturer. Our sales team can provide you with more information on the warranty period for specific products." },
    { question: "Do you offer any installation services for home appliances?", answer: "Yes, we offer installation services for home appliances, including TVs, refrigerators, and air conditioners, for a flat fee of ₹1529." },
    { question: "How can I contact AASTHA ELECTRONICS for any queries or feedback?", answer: "You can contact us at 076229 82200 or visit our store at 2,3, Naroda Business Hub, Naroda - Dehgam Rd, nr. D-Mart, Hanspura, Nava Naroda, Ahmedabad, Gujarat 382330." }] },
  ctaTitle: "Discover the Best Electronics",
  ctaDescription: "Visit us today at AASTHA ELECTRONICS and explore our wide range of electronic devices and accessories.",
  ctaButtonText: "Explore Now",
  metaDescription: "AASTHA ELECTRONICS: Your one-stop destination for electronics in Naroda, Ahmedabad.",
};

export const siteConfig = {
  layout: "luxury",
  theme: "dark",
  sections: ["testimonials", "gallery", "services", "about", "contact", "faq"],
  heroVariant: "split-screen",
  navStyle: "minimal-top-nav",
  animationStyle: "framer-motion-cinematic",
  cardStyle: "rounded-3xl shadow-lg",
  darkMode: false,
};
