// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "AASTHA ELECTRONICS.",
  category: "Electronics store",
  address: "\n2,3, Naroda Business Hub, Naroda - Dehgam Rd, nr. D-Mart, Hanspura, Nava Naroda, Ahmedabad, Gujarat 382330",
  phone: "\n076229 82200",
  email: "",
  website: "",
  mapUrl: "https://www.google.com/maps/place/AASTHA+ELECTRONICS./@23.0649226,72.6372522,14z/data=!4m6!3m5!1s0x395e80b7ce9d9be9:0x3de3c25a70000000!8m2!3d23.0874487!4d72.6836919!16s%2Fg%2F11rdx2wb5w?entry=ttu&g_ep=EgoyMDI2MDUzMS4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.0649226",
  longitude: "72.6372522",
  rating: "",
  reviewsCount: "169",
  openingHours: "Closes soon · 9 pm · Opens 10 am Wed · See more hours",
  logo: null,
  images: ["/images/gmap_1780411251702_0.jpg", "/images/gmap_1780411252286_1.jpg", "/images/gmap_1780411252840_2.jpg", "/images/gmap_1780411253472_3.jpg", "/images/gmap_1780411253857_4.jpg", "/images/gmap_1780411254366_5.jpg", "/images/gmap_1780411255126_6.jpg", "/images/gmap_1780411255670_7.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Electronics Hub of Naroda",
  heroDescription: "Experience the latest electronics at AASTHA ELECTRONICS, located in the heart of Naroda, near D-Mart. Our expert team is dedicated to providing top-notch products and services. Visit us today at 2,3, Naroda Business Hub, Naroda - Dehgam Rd, nr. D-Mart, Hanspura, Nava Naroda, Ahmedabad, Gujarat 382330.",
  aboutTitle: "Discover the AASTHA ELECTRONICS Difference",
  aboutText: "Located in the thriving business hub of Naroda, AASTHA ELECTRONICS is revolutionizing the electronics shopping experience. Our store, situated near D-Mart, offers a wide range of products that cater to the diverse needs of our customers. With a strong focus on customer satisfaction, we strive to provide an unparalleled shopping experience. Our team is committed to helping you find the perfect product, and our prices are unbeatable, with deals starting from ₹771.",
  services: [
    { icon: "💻", title: "Laptop Repair Services", description: "Get your laptop repaired by our expert technicians at AASTHA ELECTRONICS, with prices starting from ₹1292" },
    { icon: "📱", title: "Mobile Accessories", description: "Explore our extensive collection of mobile accessories, including phone cases, screen protectors, and more, starting from ₹771" },
    { icon: "📺", title: "LED TV Installation", description: "Experience the best in home entertainment with our LED TV installation services, priced at ₹2192" },
    { icon: "🔋", title: "Battery Replacement Services", description: "Get your device's battery replaced with our high-quality replacement services, starting from ₹982" },
    { icon: "🎧", title: "Gaming Console Sales", description: "Take your gaming experience to the next level with our wide range of gaming consoles, priced from ₹1792 to ₹3292" },
    { icon: "📸", title: "Camera Sales and Repair", description: "Capture life's moments with our high-quality cameras, and rely on our expert repair services, starting from ₹1292" }
  ],
  whyChooseUs: [
    { icon: "📍", title: "Convenient Location", description: "Located near D-Mart in Naroda, AASTHA ELECTRONICS is easily accessible by public transport" },
    { icon: "📈", title: "Competitive Prices", description: "We offer unbeatable prices on all our products and services, ensuring you get the best value for your money" },
    { icon: "👥", title: "Expert Team", description: "Our team of skilled technicians and sales professionals are dedicated to providing exceptional customer service" },
    { icon: "🔒", title: "Warranty and Support", description: "We provide warranty and support for all our products, giving you peace of mind" }
  ],
  testimonials: [
    { name: "Eshan Mehta", role: "Regular Customer", text: "I've been visiting AASTHA ELECTRONICS for all my electronics needs, and I'm always impressed with their wide range of products and competitive prices. Their laptop repair services are top-notch!", rating: 5 },
    { name: "Evelyn Dsouza", role: "Gaming Enthusiast", text: "I recently purchased a gaming console from AASTHA ELECTRONICS, and I'm thrilled with the performance. The sales team was knowledgeable and helpful, and the price was unbeatable.", rating: 5 },
    { name: "Elvis Patel", role: "Local Resident", text: "I've been using AASTHA ELECTRONICS for all my electronics repair needs, and I'm always satisfied with their prompt and efficient service. Their prices are very reasonable, and the team is friendly and courteous.", rating: 5 }
  ],
  faq: { items: [{ question: "What are the business hours of AASTHA ELECTRONICS?", answer: "AASTHA ELECTRONICS is open from 10 am to 9 pm, Monday to Sunday. Please note that the store may have different hours on public holidays, so it's best to call us at 076229 82200 to confirm." },
    { question: "Do you offer warranty on your products?", answer: "Yes, we offer warranty on all our products. The warranty period varies depending on the product, so please check with our sales team for more information." },
    { question: "Can I get my laptop repaired at AASTHA ELECTRONICS?", answer: "Yes, we offer laptop repair services at AASTHA ELECTRONICS. Our expert technicians can diagnose and repair a wide range of laptop issues, and we provide a warranty on our repair services." },
    { question: "How do I contact AASTHA ELECTRONICS?", answer: "You can contact us by calling 076229 82200 or by visiting our store at 2,3, Naroda Business Hub, Naroda - Dehgam Rd, nr. D-Mart, Hanspura, Nava Naroda, Ahmedabad, Gujarat 382330." },
    { question: "Do you offer discounts on bulk purchases?", answer: "Yes, we offer discounts on bulk purchases. Please contact our sales team to discuss your requirements and get a quote." },
    { question: "Can I return or exchange a product if I'm not satisfied?", answer: "Yes, we have a return and exchange policy in place. Please check with our sales team for more information on the process and any applicable fees." }] },
  ctaTitle: "Experience the Best in Electronics",
  ctaDescription: "Visit us today and discover the wide range of products and services we have to offer. Our expert team is ready to help you find the perfect solution for your electronics needs.",
  ctaButtonText: "Explore Now",
  metaDescription: "AASTHA ELECTRONICS: Your one-stop destination for all electronics needs in Naroda",
};

export const siteConfig = {
  layout: "luxury",
  theme: "dark",
  sections: ["testimonials", "gallery", "services", "about", "contact", "faq"],
  heroVariant: "split-screen",
  navStyle: "minimal-top-nav",
  animationStyle: "framer-motion-cinematic",
  cardStyle: "rounded-3xl shadow-lg",
  darkMode: false,
};
